#!/usr/bin/env bash
# selfheal.sh — given a target repo and a dependency's breaking-change notes,
# generate a migration patch and open a real PR against the target repo.
#
# This is the MVP core of "Self-Maintaining APIs": instead of a human reading
# a changelog and manually updating call sites, this script hands the
# changelog + the target codebase to Claude headless, applies whatever patch
# it produces, and opens a PR for human review before merge.
#
# Usage: ./selfheal.sh <target-repo-dir> <changelog-file>

set -euo pipefail

TARGET_DIR="${1:?usage: selfheal.sh <target-repo-dir> <changelog-file>}"
CHANGELOG_FILE="${2:?usage: selfheal.sh <target-repo-dir> <changelog-file>}"

[ -d "$TARGET_DIR/.git" ] || { echo "error: $TARGET_DIR is not a git repo" >&2; exit 1; }
[ -f "$CHANGELOG_FILE" ] || { echo "error: $CHANGELOG_FILE not found" >&2; exit 1; }

CHANGELOG_TEXT="$(cat "$CHANGELOG_FILE")"
BRANCH="selfheal/auto-migrate-$(date +%Y%m%d%H%M%S)"

cd "$TARGET_DIR"
git checkout -q -b "$BRANCH"

PROMPT="A dependency this codebase uses just published these breaking-change release notes:

---
${CHANGELOG_TEXT}
---

Find every call site in this repository affected by this change and update
them to the new API. Do not touch anything unrelated to this migration. Do
not add comments explaining the change. If a call site is ambiguous, make the
most conservative correct choice and leave the code otherwise unchanged."

echo "Running migration against: $TARGET_DIR"
claude -p "$PROMPT" </dev/null

if git diff --quiet; then
  echo "No changes were made (nothing matched, or Claude found nothing to migrate). Aborting."
  git checkout -q -
  git branch -q -D "$BRANCH"
  exit 1
fi

git add -A
git commit -q -m "$(cat <<EOF
Auto-migrate for dependency breaking change

$(head -5 "$CHANGELOG_FILE")

Generated by selfheal-cli — review before merging.
EOF
)"

git push -q -u origin "$BRANCH"

gh pr create \
  --title "selfheal: auto-migrate for upstream breaking change" \
  --body "$(cat <<EOF
Automated migration PR generated by [selfheal-cli](https://github.com/tsushanth/selfheal-cli)
in response to this upstream changelog:

\`\`\`
${CHANGELOG_TEXT}
\`\`\`

**This PR was generated by an automated tool and has not been human-reviewed
for correctness.** Review the diff carefully before merging.
EOF
)"

echo "Opened PR on branch $BRANCH"
